################################################
#                  BUILD
################################################

intel.b.ldap-sdk-tools:
  stage: products
  script:
    - ci_scripts/build_product.sh --product ldap-sdk-tools
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)ldap-sdk-tools(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - ldap-sdk-tools/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.b.ldap-sdk-tools:
  stage: products
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/build_product.sh --product ldap-sdk-tools
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)ldap-sdk-tools(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - ldap-sdk-tools/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  SMOKE TESTS
################################################

intel.t.ldap-sdk-tools:
  stage: test.smoke
  script:
    - ci_scripts/run_helm_smoke.sh --product ldap-sdk-tools
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)ldap-sdk-tools(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - ldap-sdk-tools/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/ldap-sdk-tools/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

arm.t.ldap-sdk-tools:
  stage: test.smoke
  image: $RUNNER_IMAGE_AARCH64
  tags:
    - platform=aarch64
  script:
    - ci_scripts/run_helm_smoke.sh --product ldap-sdk-tools
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip tests\]|\[skip smoke\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)ldap-sdk-tools(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_PIPELINE_SOURCE =~ /^push$/'
      changes:
        - ldap-sdk-tools/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
        - helm-tests/smoke-tests/ldap-sdk-tools/*
      when: on_success
    - if: '$CI_PIPELINE_SOURCE =~ /^schedule$|^web$/'
      when: on_success

################################################
#                  DEPLOY
################################################

d.ldap-sdk-tools:
  stage: deploy
  script:
    - ci_scripts/deploy_product_to_registry.sh --product ldap-sdk-tools
    - ci_scripts/deploy_manifests_to_registry.sh --product ldap-sdk-tools
  rules:
    - if: $ARCHIVE_PIPELINE == "true"
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]|\[skip products\]|\[skip deploy\]/i'
      when: never
    - if: '$BUILD_PRODUCT != null && $BUILD_PRODUCT =~ /(?:^|,)ldap-sdk-tools(?:$|,)/i'
      when: on_success
    - if: '$BUILD_PRODUCT != null'
      when: never
    - if: '$PING_IDENTITY_SNAPSHOT =~ /--snapshot/'
      when: never
    - if: '$CI_COMMIT_REF_NAME =~ /^master$/'
      changes:
        - ldap-sdk-tools/**/*
        - ci_scripts/*
        - pingjvm/*
        - .gitlab-ci.yml
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^\d{4}\.?\d*/'
      when: on_success
